- name: Add local0.* /var/log/pssid.log to rsyslog.conf
  blockinfile:
    path: /etc/rsyslog.conf
    block: |
      local0.* /var/log/pssid.log
  notify: restart rsyslog

  - name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
