- name: Create systemd service file
  template:
    src: pssid-daemon.service.j2
    dest: /etc/systemd/system/pssid-daemon.service
  notify: 
    - Reload systemd

# - name: Reload systemd
#   systemd:
#     daemon_reexec: yes
#   notify: 
#     - Restart pssid-daemon

- name: Reload systemd configuration
  systemd:
    daemon_reload: yes

- name: Restart pssid-daemon service
  systemd:
    name: pssid-daemon.service
    state: restarted

- name: Check status of pssid-daemon service
  systemd:
    name: pssid-daemon.service
    state: started
    enabled: yes
  register: pssid_status

- name: Print pssid-daemon service status
  debug:
    msg: "pssid-daemon service status: {{ pssid_status }}"

- name: Enable pssid-daemon service at boot
  systemd:
    name: pssid-daemon.service
    enabled: yes