- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install iw
  apt:
    name: iw
    state: present

- name: Install croniter Python package
  pip:
    name: croniter

# - name: install erfSONAR
#   script:
#     incline: |
#       curl -s curl -s https://raw.githubusercontent.com/perfsonar/project/master/install-perfsonar | sudo sh -s -- --auto-updates --tunings testpoint


# - name: perfSONAR installation script
#   # shell: curl -s https://raw.githubusercontent.com/perfsonar/project/master/install-perfsonar | sudo sh -s -- --auto-updates --tunings testpoint
#   shell: curl -s https://raw.githubusercontent.com/perfsonar/project/installation-script/install-perfsonar | sh -s - --repo staging testpoint

- name: Download perfSONAR installation script
  get_url:
    url: https://raw.githubusercontent.com/perfsonar/project/master/install-perfsonar
    dest: /tmp/install-perfsonar
    mode: 0755  # Ensure executable permissions
  register: download_result
  changed_when: download_result.changed

- name: Execute perfSONAR installation script
  command: /tmp/install-perfsonar --auto-updates --tunings testpoint
  args:
    executable: /bin/sh
  when: download_result.changed  # Execute only if the download was successful