- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install iw
  apt:
    name: iw
    state: present

- name: Install croniter Python package
  pip:
    name: croniter

- name: install erfSONAR
  script:
    incline: |
      curl -s curl -s https://raw.githubusercontent.com/perfsonar/project/master/install-perfsonar | sudo sh -s -- --auto-updates --tunings testpoint


# - name: perfSONAR installation script
#   # shell: curl -s https://raw.githubusercontent.com/perfsonar/project/master/install-perfsonar | sudo sh -s -- --auto-updates --tunings testpoint
#   shell: curl -s https://raw.githubusercontent.com/perfsonar/project/installation-script/install-perfsonar | sh -s - --repo staging testpoint

