- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install iw
  apt:
    name: iw
    state: present

- name: Install croniter Python package
  pip:
    name: croniter